import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "./context/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="flex">
            <Link className="px-9 border border-cyan-50" href={'/signup'}>Signup</Link>
            <Link className="px-9 border border-cyan-50" href={'/login'}>login</Link>
            <Link className="px-9 border border-cyan-50" href={'/about'}>about</Link>
            <Link className="px-9 border border-cyan-50" href={'/'}>Home</Link>
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
